# llama.cpp serer docs:
# https://github.com/ggerganov/llama.cpp/blob/master/examples/server/README.md
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-cpp-server
spec:
  selector:
    matchLabels:
      app: llama-cpp-server
  template:
    metadata:
      labels:
        app: llama-cpp-server
    spec:
      containers:
        - name: llama-cpp-server
          image: ghcr.io/ggerganov/llama.cpp:server
          args: [
              "--host",
              "0.0.0.0",
              "--port",
              "1234",
              "--model",
              "/models/PsiPi/liuhaotian_llava-v1.5-13b-GGUF/llava-v1.5-13b-Q2_K.gguf",
              # multimodal models need --mmproj to be provided too
              "--mmproj",
              "/models/PsiPi/liuhaotian_llava-v1.5-13b-GGUF/mmproj-model-Q4_0.gguf",
            ]
          resources:
            requests:
              cpu: 4000m
              memory: 2Gi
            limits:
              cpu: 16000m
              memory: 16Gi
          ports:
            - containerPort: 1234
          volumeMounts:
            - name: models
              mountPath: /models
              mountPropagation: HostToContainer
              readOnly: true
      volumes:
        - name: models
          hostPath:
            path: /media/plugin-data/llama-cpp-models
