apiVersion: v1
kind: Service
metadata:
  name: llama-cpp-server
spec:
  selector:
    app: llama-cpp-server
  ports:
    - name: http
      port: 1234
---
apiVersion: v1
kind: Service
metadata:
  name: llama-cpp-server-host
spec:
  type: NodePort
  selector:
    app: llama-cpp-server-host
  ports:
    - name: http
      port: 1234
      nodePort: 30000
